version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    deploy:
        resources:
            limits:
              cpus: "0.50"
              memory: 2048M
            reservations:
              cpus: "0.25"
              memory: 1024M
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - test

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    ports:
      - "5601:5601"
    networks:
      - test

  elasticsearch-api:
    image: estudo/elasticsearch:runtime
    container_name: elasticsearch-api
    build:
      context: ./ElasticSearchSample
      dockerfile: ./ElasticSearchSample/Dockerfile
    ports: 
      - 80:80
      - 443:443
    networks:
      - test

networks:
  test:
    driver: bridge